[project]
site_name = "jmapc"
site_description = "A JMAP client library for Python"
site_author = "Stephen Kent"
site_url = "https://smkent.github.io/jmapc"
repo_url = "https://github.com/smkent/jmapc"
repo_name = "smkent/jmapc"
copyright = "&copy; 2022 Stephen Kent"

nav = [
  { "About" = [
    "index.md",
    "license.md",
    "contributing.md",
    { "Development" = [
      "development/requirements.md",
      "development/workflow.md",
      "development/updates.md",
    ] },
    { "Project Operations" = [
      "setup.md",
      "releasing.md",
    ] },
  ] },
  { "API Reference" = "api.md" },
]

# ----------------------------------------------------------------------------
# Theme
# ----------------------------------------------------------------------------
[project.theme]
language = "en"
features = [
  "content.code.annotate",
  "content.code.copy",
  "content.tooltips",
  "navigation.expand",
  "navigation.footer",
  "navigation.instant",
  "navigation.path",
  "navigation.sections",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.top",
  "search.highlight",
  "toc.follow",
]

[project.theme.icon]
logo = "lucide/at-sign"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "material/brightness-auto"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "teal"
accent = "purple"
toggle.icon = "material/weather-sunny"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "black"
accent = "lime"
toggle.icon = "material/weather-night"
toggle.name = "Switch to system preference"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/smkent/jmapc"

[[project.extra.social]]
icon = "fontawesome/brands/python"
link = "https://pypi.org/project/jmapc/"

# ----------------------------------------------------------------------------
# Markdown extensions
# ----------------------------------------------------------------------------
[project.markdown_extensions.admonition]

[project.markdown_extensions.attr_list]

[project.markdown_extensions.def_list]

[project.markdown_extensions.footnotes]

[project.markdown_extensions.md_in_html]

[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.highlight]

[project.markdown_extensions.pymdownx.inlinehilite]

[project.markdown_extensions.pymdownx.snippets]
base_path = ["."]
check_paths = true

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

# ----------------------------------------------------------------------------
# Plugins
# ----------------------------------------------------------------------------
[project.plugins.mkdocstrings.handlers.python]
paths = ["."]
inventories = ["https://docs.python.org/3/objects.inv"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_section_style = "list"
filters = "public"
heading_level = 1
merge_init_into_class = true
separate_signature = true
show_root_heading = true
show_root_full_path = false
show_signature_annotations = true
show_source = true
show_symbol_type_heading = true
show_symbol_type_toc = true
