name: Set up Python project with Poetry

inputs:
  python_version:
    description: "Python version to install"
    required: true
  poetry_version:
    description: "Poetry version to install"
    required: true

runs:
  using: composite
  steps:
    - name: ✨ Install Poetry
      shell: bash
      run: |
        python3 -m pip install \
            "poetry==${{ inputs.poetry_version }}.*" \
            "poetry-dynamic-versioning"
        python3 -m pip install --upgrade requests

    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      id: setuppy
      with:
        python-version: ${{ inputs.python_version }}
        cache: poetry

    - name: 🛠️ Install project and dependencies
      shell: bash
      env:
        # https://github.com/python-poetry/poetry/issues/1917
        # https://github.com/actions/runner-images/issues/6185
        PYTHON_KEYRING_BACKEND: "keyring.backends.null.Keyring"
      run: |
        poetry install
        poetry lock --check
        PROJECT_VERSION=$(poetry version -s)
        [ "${PROJECT_VERSION}" != "0.0.0" ] \
            || { echo "Versioning broken"; exit 1; }
        echo "PROJECT_VERSION=${PROJECT_VERSION}" >> $GITHUB_ENV

    - name: 🪝 Cache pre-commit hooks
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: "pre-commit-${{ runner.os }}-python\
          -${{ steps.setuppy.outputs.python-version }}\
          -${{ hashFiles('.pre-commit-config.yaml') }}"
