name: Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: 💾 Check out repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 🦀 Set up Python project with uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          python-version: '3.14'

      - name: 🐍 Install dependencies
        run: uv sync

      - name: 📖 Build documentation
        run: uv run poe docs-build

      - name: 🔼 Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: site/

  deploy:
    name: Deploy Documentation
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 🚀 Deploy site
        uses: actions/deploy-pages@v5
        id: deployment
