name: Release

on:
  push:
    tags:
      - v[0-9]*.[0-9]*

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    env:
      UV_PYTHON: '3.14'
    steps:
      - name: 💾 Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: 📦 Cache uv managed packages
        uses: actions/cache@v6
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: 🍳 Set up mise
        uses: jdx/mise-action@v4
        with:
          cache: true
          install: true

      - name: 📦 Build package
        run: mise run build

      - name: 🔼 Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/

  release:
    name: Create GitHub release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 💾 Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: 🔽 Download artifact
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/

      - name: 🏷️ Create GitHub release
        run: gh release create ${{ github.ref_name }} dist/* --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/jmapc/
    permissions:
      id-token: write
      attestations: write
    steps:
      - name: 🔽 Download artifact
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/

      - name: ☢️ Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
